export const listSuggest = {
  'find-motel': [
    'yentinh',
    'gantruong',
    'ganquanan',
    'gantaphoa',
    'giasinhvien',
    '2nguoio',
    '3nguoio',
    '4nguoio',
    'thoigiantudo',
    'anninh',
    'timnhatro',
    'timphongtro',
    'sinhvien',
    'nhatrogiare',
    'timnhacapbach',
    'capbach',
    'sachse',
    'vesinh',
    'tansinhvien',
    'thuetro',
  ],
  'find-roommate': [
    'thoigiantudo',
    'nam',
    'nu',
    'vuivehoadong',
    'giuimlang',
    'trungthuc',
    'giuvesinh',
    'nauanchung',
    'chungtruong',
    'tansinhvien',
    'thaidotot',
    'sinhvien',
    'oghep',
    'tontrong',
  ],
  review: [
    'danhgianhatro',
    'sachse',
    'yentinh',
    'dedilai',
    'gantruong',
    'anninh',
    'hangxomthanthien',
    'chonotientro',
    'nhatrochosinhvien',
    'binhdan',
    'nenthue',
    'khongnenthue',
  ],
  'find-motel-addi': [
    'Yên tĩnh',
    'Gần trường học',
    'Có thể đi bộ đến trường',
    'Gần siêu thị/tạp hóa/chợ',
    'Điện nước thoải mái',
    'Thời gian tự do',
    'Khóa cổng lúc 23 giờ',
    'Có camera an ninh',
    'Vệ sinh sạch sẽ',
    'Có dụng cụ vệ sinh',
    'Có hỗ trợ internet',
    'Vị trí trên mặt tiền',
    'Vị trí trong hẻm',
    'Không ở ghép',
  ],
  'find-roommate-addi': [
    'Giờ giấc tự do',
    'Giới tính nam',
    'Giới tính nữ',
    'Tính tình vui vẻ',
    'Hạn chế gây ồn ào',
    'Tuân thủ pháp luật',
    'Giữ vệ sinh chung',
    'Học cùng trường',
    'Dùng chung nhà bếp/giường/tủ',
    'Tôn trọng lẫn nhau',
    'Là sinh viên',
    'Ý thức tốt',
    'Có trách nhiệm',
  ],
};
