POST http://localhost:5000/api/register
Content-Type: application/json

{
"username":"deptrainhat",
"password":"admin",
"name":"Nguyễn Tấn Mãi ĐẸP TRAIdddd12dddddddddsss",
"email":"hihdidddddd12dddddddsddss@gmail.com",
"district":"huyen_chau_thanh",
"province":"tinh_tien_giang",
"school":"truong_dai_hoc_tien_giang_tcn"
}
###
DELETE http://localhost:5000/api/users/613b466111d0f24b575a9e8f
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxMzllMzc4ZGMxZTljYzkwYThlZGZkNCIsImlzQWRtaW4iOnRydWUsImlhdCI6MTYzMTI3NDk0MiwiZXhwIjoxNjMxMjc1NTQyfQ.-z3HGNPkdqhYoaLMUo6wt2cdXz63nKBLybwpqn-eXnY
###
GET http://localhost:5000/api/
###
POST http://localhost:5000/api/login
Content-Type: application/json
//Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxMzM1NTFmZTI1Zjc4ZTEyOTA5YzFlYSIsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE2MzA3NTQwNzksImV4cCI6MTYzMDc1NDY3OX0.frCvIwZSF4kIEZHPDKww0z2yDVFOWxwXxMPoIquMbLg

 {
    "username":"admin",
    "password":"123456"
     //"accessToken":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxMmNjMjIwMDUyNzRkNjg1ZWRiZTRkNyIsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE2MzA3MTc4NDYsImV4cCI6MTYzMDcxNzkwNn0.sNtYRra6sUjZZkOikAyhlY8FdbXTwTksePSBNLjoRLI"
 }

###
POST http://localhost:5000/api/forgot-password
Content-Type: application/json

{
    "email":"killdogvinam@gmail.com"
}
###
GET http://localhost:5000/api/reset-password/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiNjEyODlmMWMyZTVkMWY0MDdiMGEyNzFmIiwiaWF0IjoxNjMwMDY1NzAwLCJleHAiOjE2MzAwNjc1MDB9.lb24sbXuHo5ylAASqCPc0tB8V4L7Sr7iXbBPhmzEce4


###
POST http://localhost:5000/api/reset-password/
Content-Type: application/json

{
    "password":"1234567",
    "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxMmNjMjIwMDUyNzRkNjg1ZWRiZTRkNyIsImlhdCI6MTYzMDU2MjE0NCwiZXhwIjoxNjMwNTYyNzQ0fQ.pE-hb1XIZES702cr02wyHXWuZRPLbocfcljYoMQHjs4"
}
###
GET http://localhost:5000/api/provinces
###

GET http://localhost:5000/api/districts?province=thanh_pho_ha_noi

###

GET http://localhost:5000/api/schools?province=thanh_pho_ho_chi_minh&district=quan_9

###
POST http://localhost:5000/api/refresh-token
Content-Type: application/json

{
    "refreshToken":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxM2YyODM0MGEwZjY4ZDQxYzAwMWIxYyIsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE2MzE1ODk2MzN9.6s96mM7pVh-4tgLK0emVRbKJkn03jbPG5y8toDq-xHg"
} 
###

GET http://localhost:5000/api/users/?_role=user
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxMmNjMjIwMDUyNzRkNjg1ZWRiZTRkNyIsImlzQWRtaW4iOnRydWUsImlhdCI6MTYzMTA4NDYyNiwiZXhwIjoxNjMxMDg1MjI2fQ.KItpbh8nSNWvDlOltIkM6xOjpbR98d9_jy0SgWYWu6g

###
PUT http://localhost:5000/api/user/612cc22005274d685edbe4d7
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxMmNjMjIwMDUyNzRkNjg1ZWRiZTRkNyIsImlzQWRtaW4iOnRydWUsImlhdCI6MTYzMTA4NTE5NiwiZXhwIjoxNjMxMDg1Nzk2fQ.Wy_83T6YYMBfG7CDxXyHSw1GFD2vIE1A9e6zdZH2fdw

{
    "tokenId":"4/0AX4XfWjDvzNuBXggSEKhZYKRr0URYMlfiP6v1m3-hgn2H9hR6yXJMHL8FwUGqd_6KbyzhA"
}

###
# @name GetUserByNamelike
GET  http://localhost:5000/api/users?_page=1&_limit=10&_sort=credit&_order=desc
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxMzllMzc4ZGMxZTljYzkwYThlZGZkNCIsImlzQWRtaW4iOnRydWUsImlhdCI6MTYzMTE5NjA3MiwiZXhwIjoxNjMxMTk2NjcyfQ.IDbPq_yEos9NYQa8TvTzR9l_w7doqIW9L9HqbtyeDco

###
DELETE http://localhost:5000/api/users/612cc22005274d685edbe4d7
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxMmNlMDJmZDc1YTA1OTczYTc2M2JmNCIsImlzQWRtaW4iOnRydWUsImlhdCI6MTYzMTA5MTQwMSwiZXhwIjoxNjMxMDkyMDAxfQ.ht6KBrOwMWBXZKWE3-vjnwP55UBsSwet0pq3lr7avvw
{
    "password":"1234567",
    "newPassword":"01234567"
}
###
POST http://localhost:5000/api/logout
Content-Type: application/json
###
GET  http://localhost:5000/api/districts

###
POST http://localhost:5000/api/motels
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxM2M3ZTNjY2Q5NTQ0YWU1MGUyNjlkZCIsImlzQWRtaW4iOnRydWUsImlhdCI6MTYzMTc4NzA5OSwiZXhwIjoxNjMxNzg3Njk5fQ.o8H2bqD9lZlmcCW5l9oMg6ZL0K_eIshsUMo9Lm8cTsA

{
    "name":"NGUYEN TAN MAI qua dep trai", 
    "images":[{"url":"https://res.cloudinary.com/dpregsdt9/image/upload/v1631509899/motel/thiet-ke-phong-tro-3_hilstc.jpg","public_id":"motel/thiet-ke-phong-tro-3_hilstc"}], 
    "address":"C45P+HQF, Nhị Mỹ, Cai Lậy, Tiền Giang", 
    "thumbnail":{"url":"https://res.cloudinary.com/dpregsdt9/image/upload/v1631509940/motel/phong_tro_nho_12m_iyxoqg.jpg","public_id":"motel/phong_tro_nho_12m_iyxoqg"},
    "room":[{
        "area":{
            "width":3,
            "length":4
        },
        "optional":{
            //Có giường thường
            "GIUONG": false,
            //Có máy lạnh =>
            "MAYLANH": true,
            //Có quạt =>
            "QUAT": false,
            //Có gác =>
            "GAC": true,
            // Chung chủ =>
            "CHUNGCHU": false,
            //Trên lầu =>
            "LAU": true,
            //Có giường tầng =>
            "GIUONGTANG": false,
            //Có nhà xe =>
            "NHAXE": false,
            //Có camera =>
            "CAMERA": false,
            //Co Wifi =>
            "WIFI": false,
            //Có dung cu vệ sinh
            "DUNGCUVESINH": false,
            //Khác =>
            "KHAC": false
        },
        "total":10,
        "remain":4,
        "price":500000
    }],
    "desc":"Gara ô tô phía ngoài có mái che, có thể chứa được 4 xe ô tô, thuận tiện cho quá trình đi lại. Mảng tường ở tầng 1 được ốp đá mang lại sự chắc chắn, mạnh mẽ cho ngôi nhà.<br/><br/> Hệ thống cửa được làm từ những ô kính lớn, đặc biệt là khoảng giữa nhà là khoảng không gian thông tầng mảng tường được thay bằng cửa kính tạo không gian mở, giúp ngôi nhà thông sáng, mang một vẻ đẹp mỏng manh, tinh tế", 
    "contact":{"zalo":"0987654321","facebook":"askasduhd"},
    "status":true,
    "avalaible":6,
    "school":["6139d5d6d02c8be6b20880cc"]
}

###
GET http://localhost:5000/api/motels?_school=6139d5d6d02c8be6b20880cc
###
GET http://localhost:5000/api/motels/?_keysearch=ad
###
POST http://localhost:5000/api/motels/rates/615a9f13dc19793cda17890f
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxM2M3ZTNjY2Q5NTQ0YWU1MGUyNjlkZCIsImlzQWRtaW4iOnRydWUsImlhdCI6MTYzMzMzODc3NiwiZXhwIjoxNjMzMzM5Mzc2fQ.rJ6nqJLbC5SxmOYfmLDHr3PK-Aji7HoYkRSTmVBaXws

{
    "content":"Tui rất thích nhà trọ này",
    "star":5
}
###
PATCH http://localhost:5000/api/motels/rates/6145d3d6c74fc7d6fd42b263/61468c6b3d558bfe08a13ac9/
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxM2M3ZTNjY2Q5NTQ0YWU1MGUyNjlkZCIsImlzQWRtaW4iOnRydWUsImlhdCI6MTYzMzMzODc3NiwiZXhwIjoxNjMzMzM5Mzc2fQ.rJ6nqJLbC5SxmOYfmLDHr3PK-Aji7HoYkRSTmVBaXws

{
    "content":"Tui rất thích nhà trọ này à nha ",
    "star":5
}
###
DELETE  http://localhost:5000/api/motels/rates/6145d3d6c74fc7d6fd42b263/61468c6b3d558bfe08a13ac9
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxM2M3ZTNjY2Q5NTQ0YWU1MGUyNjlkZCIsImlzQWRtaW4iOnRydWUsImlhdCI6MTYzMjAyMjUxMiwiZXhwIjoxNjMyMDIzMTEyfQ.-SZha78wf4nnAShyAkmNXoiq6mZtl1pAoFTX2Y4-25w
###
PATCH http://localhost:5000/api/motels/rooms/615a9f13dc19793cda17890f/615a9f13dc19793cda178911
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxM2M3ZTNjY2Q5NTQ0YWU1MGUyNjlkZCIsImlzQWRtaW4iOnRydWUsImlhdCI6MTYzMzMzNzEzMCwiZXhwIjoxNjMzMzM3NzMwfQ.pBOfB1B1lMNXQHISMXwE92XXE1Jdne8xwv4oKIVBu9w

{
    "optional":["wifi","ml","cc","gt","dcvs"],
    "area":{"width":5,"length":3}
}
###
PATCH http://localhost:5000/api/motels/614542cf9f478425c2c07317
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxM2M3ZTNjY2Q5NTQ0YWU1MGUyNjlkZCIsImlzQWRtaW4iOnRydWUsImlhdCI6MTYzMjU2ODA2NiwiZXhwIjoxNjMyNTY4NjY2fQ.unr3GP3bvLlJvYUgjogXWcbu3YqZGNGKKbOiPG6j-Bw

{
    "available":12
}
###
POST http://localhost:5000/api/users/favorites/615a9f13dc19793cda17890f
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxM2M3ZTNjY2Q5NTQ0YWU1MGUyNjlkZCIsImlzQWRtaW4iOnRydWUsImlhdCI6MTYzMzQyNTExNSwiZXhwIjoxNjMzNDI1NzE1fQ.tSrR6X4RfvqLiBAzsETHcxNDz1TzS91I2Meq7R607Iw

{}