POST http://localhost:5000/api/register
Content-Type: application/json

{
"username":"heheheheheddddd1dddd2ddddddsss",
"password":"admin",
"name":"Nguyễn Tấn Mãi ĐẸP TRAIdddd12dddddddddsss",
"avatarUrl":"dajdwddd",
"email":"hihdidddddd12dddddsddss@gmail.com",
"district":"huyen_chau_thanh",
"province":"tinh_tien_giang",
"school":"truong_dai_hoc_tien_giang_tcn"
}

###
GET http://localhost:5000/api/
###
POST http://localhost:5000/api/login
Content-Type: application/json
//Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxMzM1NTFmZTI1Zjc4ZTEyOTA5YzFlYSIsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE2MzA3NTQwNzksImV4cCI6MTYzMDc1NDY3OX0.frCvIwZSF4kIEZHPDKww0z2yDVFOWxwXxMPoIquMbLg

 {
    "username":"minhtai",
    "password":"123456789"
     //"accessToken":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxMmNjMjIwMDUyNzRkNjg1ZWRiZTRkNyIsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE2MzA3MTc4NDYsImV4cCI6MTYzMDcxNzkwNn0.sNtYRra6sUjZZkOikAyhlY8FdbXTwTksePSBNLjoRLI"
 }

###
POST http://localhost:5000/api/forgot-password
Content-Type: application/json

{
    "email":"killdogvinam@gmail.com"
}
###
GET http://localhost:5000/api/reset-password/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiNjEyODlmMWMyZTVkMWY0MDdiMGEyNzFmIiwiaWF0IjoxNjMwMDY1NzAwLCJleHAiOjE2MzAwNjc1MDB9.lb24sbXuHo5ylAASqCPc0tB8V4L7Sr7iXbBPhmzEce4


###
POST http://localhost:5000/api/reset-password/
Content-Type: application/json

{
    "password":"1234567",
    "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxMmNjMjIwMDUyNzRkNjg1ZWRiZTRkNyIsImlhdCI6MTYzMDU2MjE0NCwiZXhwIjoxNjMwNTYyNzQ0fQ.pE-hb1XIZES702cr02wyHXWuZRPLbocfcljYoMQHjs4"
}
###
GET http://localhost:5000/api/provinces
###

GET http://localhost:5000/api/districts?province=thanh_pho_ha_noi

###

GET http://localhost:5000/api/schools?province=thanh_pho_ho_chi_minh&district=quan_9

###
POST http://localhost:5000/api/refresh-token
Content-Type: application/json

{
    "refreshToken":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxMzM1NTFmZTI1Zjc4ZTEyOTA5YzFlYSIsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE2MzA3NTgxMzl9.y2aih0S0nPtJtGv74InFRD_8pBPKzMW6-H7BX59Itws"
} 
###

GET http://localhost:5000/api/users/?_role=user
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxMmNjMjIwMDUyNzRkNjg1ZWRiZTRkNyIsImlzQWRtaW4iOnRydWUsImlhdCI6MTYzMTA4NDYyNiwiZXhwIjoxNjMxMDg1MjI2fQ.KItpbh8nSNWvDlOltIkM6xOjpbR98d9_jy0SgWYWu6g

###
PUT http://localhost:5000/api/user/612cc22005274d685edbe4d7
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxMmNjMjIwMDUyNzRkNjg1ZWRiZTRkNyIsImlzQWRtaW4iOnRydWUsImlhdCI6MTYzMTA4NTE5NiwiZXhwIjoxNjMxMDg1Nzk2fQ.Wy_83T6YYMBfG7CDxXyHSw1GFD2vIE1A9e6zdZH2fdw

{
    "tokenId":"4/0AX4XfWjDvzNuBXggSEKhZYKRr0URYMlfiP6v1m3-hgn2H9hR6yXJMHL8FwUGqd_6KbyzhA"
}

###
# @name GetUserByNamelike
GET  http://localhost:5000/api/users?_page=1&_limit=10&_keysearch=fffffffffff
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxMmNlMDJmZDc1YTA1OTczYTc2M2JmNCIsImlzQWRtaW4iOnRydWUsImlhdCI6MTYzMTE1OTUxMSwiZXhwIjoxNjMxMTYwMTExfQ.lW6-GIUNyuOZGCLmV-G9_6-XGOMSO91zO9ed2YV6L38

###
DELETE http://localhost:5000/api/users/612cc22005274d685edbe4d7
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxMmNlMDJmZDc1YTA1OTczYTc2M2JmNCIsImlzQWRtaW4iOnRydWUsImlhdCI6MTYzMTA5MTQwMSwiZXhwIjoxNjMxMDkyMDAxfQ.ht6KBrOwMWBXZKWE3-vjnwP55UBsSwet0pq3lr7avvw
{
    "password":"1234567",
    "newPassword":"01234567"
}
###
GET http://localhost:5000/api/logout
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxMmNjMjIwMDUyNzRkNjg1ZWRiZTRkNyIsImlzQWRtaW4iOnRydWUsImlhdCI6MTYzMTAwODE3OH0.BQcvSs5Mm6vSQRp8ej-CJAXv7iR9S0GVbcbGBKYlZZQ
